### ISSUE TITLE
array nodes

### ISSUE THREAD

**Issue by nadimtuhin** [otalk/jxt#12]
how do we do something like
```
        <occupants>
            <user affiliation='member'>user1@shakespeare.lit</user>
            <user affiliation='member'>user2@shakespeare.lit</user>
        </occupants>

``` 

from 

```
            occupants = [{
                    affiliation: 'member',
                    jid: 'user1@shakespeare.lit'
             }, {
                    affiliation: 'member',
                    jid: 'user2@shakespeare.lit'
             }]
```

**Comment by nadimtuhin** [comment]
fixed
```
    fields: {
        namespace: helpers.attribute('xmlns'),
        occupants: helpers.subMultiExtension('', 'occupants', User)
    }
```

**Comment by jlibrun22** [comment]
An extension to this question what if I also what to add element within a node with multiple of the same type.
For example, I want to do something like

<occupants>
            <user affiliation='member'>user1@shakespeare.lit</user>
            <user affiliation='member'>user2@shakespeare.lit</user>
            <someValue = 'foo'/>
            <anotherOne= 'bar'/>
</occupants>

and use it like this



> occupants = {
    user:[object1,object2],
    someValue:'foo',
    anotherOne:'bar'

}
